{"uuid": "f4db4a38-10f1-46e8-b634-a4cac6eae371", "children": ["e9f01494-f37e-413c-be1a-551844b3129e"], "befores": [{"name": "driver", "status": "passed", "start": 1685823720114, "stop": 1685823722827}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: This alert appeared after 5 seconds\nMessage: unexpected alert open: {Alert text : This alert appeared after 5 seconds}\n  (Session info: chrome=113.0.5672.127)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x010B8893+48451]\n\t(No symbol) [0x0104B8A1]\n\t(No symbol) [0x00F55058]\n\t(No symbol) [0x00FAC90D]\n\t(No symbol) [0x00F9A0B6]\n\t(No symbol) [0x00F77E08]\n\t(No symbol) [0x00F78F2D]\n\tGetHandleVerifier [0x01318E3A+2540266]\n\tGetHandleVerifier [0x01358959+2801161]\n\tGetHandleVerifier [0x0135295C+2776588]\n\tGetHandleVerifier [0x01142280+612144]\n\t(No symbol) [0x01054F6C]\n\t(No symbol) [0x010511D8]\n\t(No symbol) [0x010512BB]\n\t(No symbol) [0x01044857]\n\tBaseThreadInitThunk [0x766E00C9+25]\n\tRtlGetAppContainerNamedObjectPath [0x77087B4E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77087B1E+238]\n\n", "trace": "  File \"D:\\automation_qa\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"D:\\automation_qa\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in _teardown_yield_fixture\n    next(it)\n  File \"D:\\automation_qa\\conftest.py\", line 17, in driver\n    attach = driver.get_screenshot_as_png()\n  File \"D:\\automation_qa\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 927, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n  File \"D:\\automation_qa\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 938, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n  File \"D:\\automation_qa\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\automation_qa\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 244, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n"}, "start": 1685823741135, "stop": 1685823741139}], "start": 1685823720114, "stop": 1685823741139}